# Tier 2 platforms are expected to be compiled.
# There are no guarantees provided for code correctness on these platforms.

on: [push, pull_request]

name: Tier 2 CI

jobs:
  tier2_ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # ARM targets were added in order to guarantee that `nushell` crate
          # will be able to compile correctly.
          # See https://github.com/nushell/nushell/issues/485

          # ARM64
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          # ARMv7
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          # ARMv6
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-gnueabihf
          - arm-unknown-linux-musleabi
          - arm-unknown-linux-musleabihf

        runtime:
          - runtime-tokio
          - runtime-async-std
          - runtime-polyfill
    steps:
      - uses: actions/checkout@v2

      - name: Cache rustup toolchain
        uses: actions/cache@v1
        with:
          path: ~/.rustup/toolchains
          key: rustup-toolchain-stable
      - name: Cache cargo build target
        uses: actions/cache@v1
        with:
          path: target
          key: target-tier-2-${{ matrix.target }}-${{ matrix.runtime }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          use-cross: true
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features full,${{ matrix.runtime }} --target=${{ matrix.target }} --manifest-path=heim/Cargo.toml
          use-cross: true
